name: 'Markdown to Slack Block'
description: 'Transforms a markdown formatted text to Slack Block'
inputs:
  markdown:
    description: 'The markdown content to transform'
    required: true
  text:
    description: 'Text for the slack block message'
    required: false
outputs:
  slack-blocks: # id of output
    description: 'The slack-block formatted text'
runs:
  using: 'node16'
  main: 'index.js'
